export const Schema = z.object({
  系统: z.object({
    日期: z.string().prefault('无记录'),
    时间: z.string().prefault('傍晚'),
    当前所在位置: z.string().prefault('青云宗后山·隐蔽山洞'),
    聚宝盆今日已用: z.boolean().prefault(false),
    主线进度: z.string().prefault('炼气'),
  }).prefault({}),
  主角: z.object({
    修为境界: z.string().prefault('炼气初期'),
    灵根品质: z.string().prefault('废灵根'),
    持有灵石: z.coerce.number().prefault(10),
    状态: z.string().prefault('正常'),
    已修功法: z.array(z.string()).prefault([]),
  }).prefault({}),
  功法系统: z.object({
    当前主修: z.string().prefault('青云吐纳诀'),
    功法列表: z.record(z.object({
      品级: z.string(),
      属性: z.string(),
      熟练度: z.string(),
    })).prefault({}),
  }).prefault({}),
  储物袋: z.object({
    丹药: z.array(z.object({ 名称: z.string(), 数量: z.coerce.number(), 品级: z.string() })).prefault([]),
    法器: z.array(z.object({ 名称: z.string(), 数量: z.coerce.number(), 品级: z.string() })).prefault([]),
    材料: z.array(z.object({ 名称: z.string(), 数量: z.coerce.number() })).prefault([]),
    功法书: z.array(z.object({ 名称: z.string(), 品级: z.string() })).prefault([]),
    其他: z.array(z.object({ 名称: z.string(), 数量: z.coerce.number() })).prefault([]),
  }).prefault({}),
  仓库: z.object({
    丹药: z.array(z.object({ 名称: z.string(), 数量: z.coerce.number(), 品级: z.string() })).prefault([]),
    法器: z.array(z.object({ 名称: z.string(), 数量: z.coerce.number(), 品级: z.string() })).prefault([]),
    材料: z.array(z.object({ 名称: z.string(), 数量: z.coerce.number() })).prefault([]),
    功法书: z.array(z.object({ 名称: z.string(), 品级: z.string() })).prefault([]),
    其他: z.array(z.object({ 名称: z.string(), 数量: z.coerce.number() })).prefault([]),
  }).prefault({}),
  柳如烟: z.object({
    好感度: z.coerce.number().prefault(1),
    态度: z.string().prefault('冷漠'),
    好感阶段: z.string().prefault('初识'),
    羁绊触发: z.boolean().prefault(false),
    专属状态: z.string().prefault('普通'),
  }).prefault({}),
  苏青棠: z.object({
    好感度: z.coerce.number().prefault(1),
    态度: z.string().prefault('中立'),
    好感阶段: z.string().prefault('初识'),
    羁绊触发: z.boolean().prefault(false),
    专属状态: z.string().prefault('普通'),
  }).prefault({}),
  叶灵儿: z.object({
    好感度: z.coerce.number().prefault(3),
    态度: z.string().prefault('友好'),
    好感阶段: z.string().prefault('初识'),
    羁绊触发: z.boolean().prefault(false),
    专属状态: z.string().prefault('普通'),
  }).prefault({}),
  白素曦: z.object({
    好感度: z.coerce.number().prefault(1),
    态度: z.string().prefault('戒备'),
    好感阶段: z.string().prefault('初识'),
    羁绊触发: z.boolean().prefault(false),
    专属状态: z.string().prefault('普通'),
  }).prefault({}),
  任务: z.object({
    当前主线: z.string().prefault('灵根升级'),
    进行中支线: z.array(z.string()).prefault([]),
    已完成任务: z.array(z.string()).prefault([]),
  }).prefault({}),
  已结交NPC: z.array(z.object({
    姓名: z.string(),
    性别: z.string(),
    外貌简述: z.string(),
    修为: z.string(),
    性格: z.string(),
    好感度: z.coerce.number(),
    态度: z.string(),
    结识地点: z.string(),
    结识原因: z.string(),
    小任务: z.string().or(z.literal('')).prefault(''),
    任务奖励: z.string().or(z.literal('')).prefault(''),
  })).prefault([]),
});

export type Schema = z.output<typeof Schema>;
